services:
  postgres:
    image: postgis/postgis:16-3.5
    platform: linux/amd64
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: jakob
      POSTGRES_PASSWORD: jakob
    ports:
      - "${DB_HOST_PORT}:5432"