CREATE TABLE categories
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255),
    parent_category_id BIGINT,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE location
(
    id                UUID NOT NULL,
    coordinates       GEOMETRY(Point, 4326) NOT NULL,
    country           VARCHAR(255),
    country_code      VARCHAR(255),
    city              VARCHAR(255),
    postal_code       VARCHAR(255),
    formatted_address VARCHAR(255),
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE post_categories
(
    category_id BIGINT NOT NULL,
    post_id     UUID   NOT NULL
);

CREATE TABLE posts
(
    id          UUID         NOT NULL,
    user_id     UUID         NOT NULL,
    date        TIMESTAMP WITHOUT TIME ZONE,
    location_id UUID         NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    age_from    INTEGER      NOT NULL,
    age_to      INTEGER      NOT NULL,
    photo_url   VARCHAR(255),
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE saved_posts
(
    post_id UUID NOT NULL,
    user_id UUID NOT NULL
);

CREATE TABLE user_interests
(
    category_id BIGINT NOT NULL,
    user_id     UUID   NOT NULL
);

CREATE TABLE users
(
    id                UUID         NOT NULL,
    first_name        VARCHAR(255) NOT NULL,
    last_name         VARCHAR(255) NOT NULL,
    age               INTEGER      NOT NULL,
    phone_number      VARCHAR(255) NOT NULL,
    profile_photo_url VARCHAR(255),
    email             VARCHAR(255) NOT NULL,
    password          VARCHAR(255) NOT NULL,
    role              VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES location (id);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE post_categories
    ADD CONSTRAINT fk_poscat_on_category FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE post_categories
    ADD CONSTRAINT fk_poscat_on_post FOREIGN KEY (post_id) REFERENCES posts (id);

ALTER TABLE saved_posts
    ADD CONSTRAINT fk_savpos_on_post FOREIGN KEY (post_id) REFERENCES posts (id);

ALTER TABLE saved_posts
    ADD CONSTRAINT fk_savpos_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_interests
    ADD CONSTRAINT fk_useint_on_category FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE user_interests
    ADD CONSTRAINT fk_useint_on_user FOREIGN KEY (user_id) REFERENCES users (id);

DROP TABLE spatial_ref_sys CASCADE;


BEGIN;
INSERT INTO categories (name) VALUES
                                  ('sports'),
                                  ('music'),
                                  ('gaming'),
                                  ('outdoor'),
                                  ('creativity'),
                                  ('food'),
                                  ('tech'),
                                  ('social');

INSERT INTO categories (name, parent_category_id) VALUES
                                                      ('Football',        (SELECT id FROM categories WHERE name = 'sports')),
                                                      ('Basketball',      (SELECT id FROM categories WHERE name = 'sports')),
                                                      ('Tennis',          (SELECT id FROM categories WHERE name = 'sports')),
                                                      ('Running',         (SELECT id FROM categories WHERE name = 'sports')),
                                                      ('Cycling',         (SELECT id FROM categories WHERE name = 'sports')),
                                                      ('Playing',         (SELECT id FROM categories WHERE name = 'music')),
                                                      ('Singing',         (SELECT id FROM categories WHERE name = 'music')),
                                                      ('Concerts',        (SELECT id FROM categories WHERE name = 'music')),

                                                      ('Video Games',     (SELECT id FROM categories WHERE name = 'gaming')),
                                                      ('Board Games',     (SELECT id FROM categories WHERE name = 'gaming')),
                                                      ('Tabletop RPG',    (SELECT id FROM categories WHERE name = 'gaming')),

                                                      ('Hiking',          (SELECT id FROM categories WHERE name = 'outdoor')),
                                                      ('Camping',         (SELECT id FROM categories WHERE name = 'outdoor')),
                                                      ('Fishing',         (SELECT id FROM categories WHERE name = 'outdoor')),

                                                      ('Drawing',         (SELECT id FROM categories WHERE name = 'creativity')),
                                                      ('Painting',        (SELECT id FROM categories WHERE name = 'creativity')),
                                                      ('Photography',     (SELECT id FROM categories WHERE name = 'creativity')),
                                                      ('DIY & Crafts',    (SELECT id FROM categories WHERE name = 'creativity')),

                                                      ('Cooking',         (SELECT id FROM categories WHERE name = 'food')),
                                                      ('Baking',          (SELECT id FROM categories WHERE name = 'food')),
                                                      ('Coffee & Cafés',  (SELECT id FROM categories WHERE name = 'food')),

                                                      ('Programming',     (SELECT id FROM categories WHERE name = 'tech')),
                                                      ('Robotics',        (SELECT id FROM categories WHERE name = 'tech')),
                                                      ('Game Development',(SELECT id FROM categories WHERE name = 'tech')),

                                                      ('Language Exchange',(SELECT id FROM categories WHERE name = 'social')),
                                                      ('Volunteering',     (SELECT id FROM categories WHERE name = 'social')),
                                                      ('Networking',       (SELECT id FROM categories WHERE name = 'social')),
                                                      ('Book Clubs',       (SELECT id FROM categories WHERE name = 'social'));
COMMIT;
