CREATE TABLE categories
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255),
    parent_category_id BIGINT,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE post_categories
(
    category_id BIGINT NOT NULL,
    post_id     UUID   NOT NULL
);

CREATE TABLE posts
(
    id          UUID    NOT NULL,
    date        TIMESTAMP WITHOUT TIME ZONE,
    location    VARCHAR(255),
    user_id     UUID,
    title       VARCHAR(255),
    description VARCHAR(255),
    age_from    INTEGER NOT NULL,
    age_to      INTEGER NOT NULL,
    photo_url   VARCHAR(255),
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE user_interests
(
    category_id BIGINT NOT NULL,
    user_id     UUID   NOT NULL
);

CREATE TABLE users
(
    id                UUID         NOT NULL,
    first_name        VARCHAR(255) NOT NULL,
    last_name         VARCHAR(255) NOT NULL,
    age               INTEGER      NOT NULL,
    phone_number      VARCHAR(255) NOT NULL,
    profile_photo_url VARCHAR(255),
    email             VARCHAR(255) NOT NULL,
    role              VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE post_categories
    ADD CONSTRAINT fk_poscat_on_category FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE post_categories
    ADD CONSTRAINT fk_poscat_on_post FOREIGN KEY (post_id) REFERENCES posts (id);

ALTER TABLE user_interests
    ADD CONSTRAINT fk_useint_on_category FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE user_interests
    ADD CONSTRAINT fk_useint_on_user FOREIGN KEY (user_id) REFERENCES users (id);