CREATE TABLE user_interests
(
    user_id  BIGINT NOT NULL,
    interest VARCHAR(255)
);

CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name        VARCHAR(255)                            NOT NULL,
    last_name         VARCHAR(255)                            NOT NULL,
    age               INTEGER                                 NOT NULL,
    phone_number      VARCHAR(255)                            NOT NULL,
    profile_photo_url VARCHAR(255),
    email             VARCHAR(255)                            NOT NULL,
    role              VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

ALTER TABLE user_interests
    ADD CONSTRAINT fk_user_interests_on_user FOREIGN KEY (user_id) REFERENCES users (id);