services:
  postgres:
    image: postgis/postgis:16-3.5
    platform: linux/amd64
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_HOST_PORT}:5432"
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID: ${STORAGE_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${STORAGE_SECRET_KEY}
      S3_BUCKET: ${STORAGE_BUCKET_NAME}
    command: mini -dir=/data
    volumes:
      - ./data:/data
    ports:
      - "8333:8333"   # S3 API
      - "9333:9333"   # Master UI
      - "8888:8888"   # Filer UI
      - "23646:23646" # Admin UI