name: integration tests

run-name: Java test, compile and run
env:
  POSTGRES_DB: test 
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  DB_HOST_PORT: 5432
  DATABASE_URL: postgresql://localhost:5432/test
  STORAGE_ENDPOINT: localhost:8333
  STORAGE_BUCKET_NAME: test
  STORAGE_ACCESS_KEY: test
  STORAGE_SECRET_KEY: test
  ADMIN_EMAIL: admin@admin.com
  ADMIN_PASSWORD: admin@adm
  JWT_NAME: token
  ALLOWED_ORIGINS: localhost:3000
  TOKEN_VALIDITY_SECONDS: 3600
  JWT_SECRET_KEY: a-long-random-secret
  GOOGLE_MAPS_API_KEY: xxx
  GOOGLE_MAPS_API_BASE_URL: https://geocode.googleapis.com
  DEV_MODE: false
on:
  push:
    branches: ['development']
    paths:
      - 'api/**'
jobs:
  run-api-components:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-compose-action@v2
      - name: run-postgres-and-seaweed
        run: docker compose up -d
      - run: chmod +x mvnw
      - name: run-api
        run: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-Dspring.devtools.restart.enabled=false"
      - name: Wait for API
        run: sleep 10
      - name: Check API
        run: curl --fail http://localhost:8080/actuator/health
      - name: Stop containers
        if: always()
        run: docker compose down